import Link from 'next/link'
import React from 'react'

const page = () => {
  return (
    <>
       <div className='bg-[#012555] text-white px-10 py-20 max-md:px-4 max-md:py-8'>
        <div className='max-w-screen-2xl mx-auto px-10 max-md:px-0 flex flex-col max-sm:items-center'>
          <div>
            <h2 className='text-6xl font-bold max-lg:text-3xl w-[80%] max-sm:text-2xl max-lg:w-full max-sm:text-center'>DIAMOND SPORTS RECRUITING LLC END USER LICENSE AGREEMENT</h2>
          </div>
          <p className='mt-2 sm:text-xl text-[#E2E2E2]'>EFFECTIVE: August 3, 2024</p>
          <p className='mt-4 max-sm:text-xs max-sm:text-center'>BY INSTALLING, ACCESSING, OR UTILIZING ANY PART OF THE DIAMOND SPORTS RECRUITING LLC ("DIAMOND SPORTS RECRUITING," "Us," or "We") APPLICATION AND SERVICES, YOU ARE AGREEING TO ALL THE TERMS AND CONDITIONS OF THIS END USER LICENSE AGREEMENT ("AGREEMENT"). "YOU" ("You" or "Users") REFERS TO ATHLETES 18 YEARS OF AGE OR OLDER, SPORTS CLUB DIRECTORS OR COACHES, HIGH SCHOOL ATHLETIC DIRECTORS, COLLEGE COACHES, OWNERS OF COLLEGE RECRUITING CONSULTING BUSINESSES, AND PARENTS OF MINOR CHILDREN WHOSE PERSONAL INFORMATION IS UPLOADED BY USERS TO THE APPLICATION OR SERVICES. REFERENCES TO "YOU," "YOUR," AND "YOUR DATA" IN SECTIONS 5 AND 13 REFER TO THE PERSONAL INFORMATION AND DATA OF ATHLETES UPLOADED BY USERS AND PARENTS OF MINOR CHILDREN TO THE APPLICATION OR SERVICES. BY CLICKING "ACCEPT," YOU CONSENT TO THE USE OF SUCH PERSONAL INFORMATION AND DATA ABOUT YOU OR YOUR CHILDREN IN THE APPLICATION AND SERVICES.</p>
          <p className='max-sm:text-xs max-sm:text-center'>YOU AGREE THAT YOU WILL NOT ENTER ANY PERSONAL HEALTH INFORMATION INTO THE APPLICATION OR SERVICES WITHOUT PRIOR WRITTEN APPROVAL FROM DIAMOND SPORTS RECRUITING.</p>
        </div>
      </div>

      <div className='max-w-screen-2xl mx-auto px-10 max-md:px-4 my-20 max-md:mt-10'>
        <h2 className='text-5xl font-bold max-lg:text-3xl max-sm:text-2xl'>ARBITRATION NOTICE AND CLASS ACTION WAIVER:</h2>

        <p className='mt-4 max-sm:text-sm'>EXCEPT FOR CERTAIN TYPES OF DISPUTES DESCRIBED IN THE ARBITRATION SECTION BELOW, YOU AGREE THAT ANY DISPUTES BETWEEN YOU AND US WILL BE RESOLVED BY BINDING, INDIVIDUAL ARBITRATION AND YOU WAIVE YOUR RIGHT TO PARTICIPATE IN ANY CLASS ACTION LAWSUIT OR CLASS.</p>
        <p className='mt-4 max-sm:text-sm'>UPON ACCEPTANCE, THIS AGREEMENT BECOMES ENFORCEABLE AGAINST YOU AND ANY ENTITY THAT HAS OBTAINED THE APPLICATION AND ON WHOSE BEHALF IT IS USED. IF YOU DO NOT ACCEPT THE TERMS AND CONDITIONS OF THIS AGREEMENT, DO NOT INSTALL OR USE THE APPLICATION. THEREFORE, YOU AND DIAMOND SPORTS RECRUITING AGREE TO THE FOLLOWING:</p>
        <p className='mt-6 max-sm:text-sm'>The “Application” or “Services” consists of: (a) the Diamond Sports Recruiting proprietary web-based software-as-a-service offering, the “Diamond Sports Recruiting” (which enables student-athletes and their coaches to collaborate on the college sports recruiting process) provided in connection with an authorized link to this Agreement, including all software, code, text, graphics, logos, layouts, designs, interfaces, and other items included in or associated with the application; and (b) any files that are delivered to you by Diamond Sports Recruiting (via online transmission, through a third-party distributor, or otherwise) to patch, update, or otherwise modify the Diamond Sports Recruiting application.</p>
        <p className='mt-4 max-sm:text-sm'>The Application may provide a means for you to access one or more websites, other applications, or other products and services offered by Diamond Sports Recruiting (collectively, the “Services”), and audio and video materials, photographs, text, graphics, logos, layouts, designs, interfaces, software, data, and other content associated with the Services (“Content”). The Application, Services, and Content are copyrighted works of Diamond Sports Recruiting and may contain trademarks, service marks, trade names, and other intellectual property of Diamond Sports Recruiting.</p>
        <p className='mt-4 max-sm:text-sm'>The Application, Services, and Content, and your use of the Services, are also subject to Diamond Sports Recruiting’s Terms of Use: <Link className='text-[#00A3FF]' href={'https://diamondsportsrecruiting.com/terms-of-use'}>https://diamondsportsrecruiting.com/terms-of-use</Link> and Privacy Policy: <Link className='text-[#00A3FF]' href={'https://diamondsportsrecruiting.com/privacy-policy'}>https://diamondsportsrecruiting.com/privacy-policy</Link> (collectively “Diamond Sports Recruiting Terms”) which are incorporated into this Agreement by reference. There may also be additional terms that Diamond Sports Recruiting presents to you in connection with the Application, for example, at the time of download (“Additional Terms”). If there is a conflict between this Agreement and any Additional Terms, the Additional Terms will control unless the Additional Terms expressly provide otherwise.</p>
        <p className='mt-4 max-sm:text-sm'>The Application may use location-based services to locate you. If you choose to use the Application, you consent to Diamond Sports Recruiting and its third-party providers determining your location.</p>
        
        <h2 className='text-4xl font-bold max-lg:text-2xl max-md:text-xl mt-10'>1. CHANGES TO THIS AGREEMENT AND DIAMOND SPORTS RECRUITING TERMS</h2>
        <p className='mt-4 max-sm:text-sm'>This Agreement applies to all downloads or installations of the Application after the Effective Date above, and use of any copy of the Application downloaded or installed after the Effective Date above. Diamond Sports Recruiting may make changes to this Agreement from time to time by posting a copy of the updated Agreement on our website. Changes to this Agreement will be applicable to downloading or installation of the Application or using the Services after the effective date of the changes. If you do not agree with any changes to this Agreement, your sole remedy is not to download or install the Application after the effective date of the changes.</p>
        <p className='mt-4 max-sm:text-sm'>Diamond Sports Recruiting also may make changes to the Diamond Sports Recruiting Terms as provided therein. Such changes will apply to your use of the Application to access Services and Content after the effective date of the changes. If you do not agree with any such changes, your sole remedy is to discontinue use of the Application to access the relevant Services and Content. If you continue to use the Application to access Services and Content after the effective date of the changes, you accept all changes.</p>

        <h2 className='text-4xl font-bold max-lg:text-2xl max-md:text-xl mt-10'>2. CHANGES TO PRODUCT AND SERVICE OFFERINGS</h2>
        <p className='mt-4 max-sm:text-sm'>Diamond Sports Recruiting may change pricing for the Application, Services, and Content. We may not provide price protection or refunds due to price reductions, promotional pricing, or any other changes to pricing for any reason.</p>
        <p className='mt-4 max-sm:text-sm'>You acknowledge and agree that Diamond Sports Recruiting may suspend or discontinue offering the Application; modify the Application; change or discontinue the Services available through the Application; change how we offer and operate such Services (e.g., to begin charging a fee to access features or Content that we previously made available without charge); remove Content; impose limits on certain features or restrict your access to part or all of the Application, Services, and Content; or make other changes in Diamond Sports Recruiting’s product and service offerings at its sole discretion and with or without notice to you. We will not be liable to you or any third party for taking any of these actions and we will not be limited to the remedies above if you violate these Diamond Sports Recruiting Terms. You further acknowledge and agree that even if a copy of the Application continues to reside on your device, after we make changes in our product or services offerings, the Application may not work as it did prior to such action, and Diamond Sports Recruiting will have no liability to you or any third party as a result.</p>

        <h2 className='text-4xl font-bold max-lg:text-2xl max-md:text-xl mt-10'>3. OWNERSHIP</h2>
        <p className='mt-4 max-sm:text-sm'>You acknowledge and agree that Diamond Sports Recruiting has all rights, title, and interest in and to the Application and all intellectual property rights associated with the Application. The Application is protected by the copyright laws of the United States, international treaties and conventions, and other laws. Except as expressly stated herein, you have no intellectual property rights in the Application (including without limitation any rights to use the trademarks, trade names, service marks, logos, domain names, and other distinctive brand features), and Diamond Sports Recruiting reserves all rights not expressly granted to you. You must comply with all laws when using the Application as well as all applicable copyright, trademark, or other legal notices or restrictions.</p>

        <h2 className='text-4xl font-bold max-lg:text-2xl max-md:text-xl mt-10'>4. CONDUCT</h2>
        <p className='mt-4 max-sm:text-sm'>You will not:</p>

        <ul className='max-sm:text-sm pl-8 list-disc list-outside'>
          <li>In whole or in part, copy, reproduce, translate, modify, adapt, create derivative works based on, or reverse engineer, derive source code from, disassemble, decompile, or otherwise attempt to discover the source code of, the Application or Services, except to the extent required by applicable law;</li>
          <li>Reproduce, copy, display, screen grab, take pictures or videos of, store, perform, re-post, publish, transmit, distribute, sell, offer for sale, license, modify, reverse engineer, decompile, create derivative works, or otherwise use any portion of the content or Software offered on Application or Services for other than your own personal, non-commercial use;</li>
          <li>Install or use the Application or Services on a computer or other device that is primarily used as a file server;</li>
          <li>Remove, obscure, or alter any copyright, trademark, logo, or other proprietary notices in or on the Application or Services;</li>
          <li>Use any unauthorized third-party software that intercepts, “mines,” or otherwise collects information from or through the Application or Services, unless authorized by Diamond Sports Recruiting in its sole discretion;</li>
          <li>Distribute, publish, display, perform, sell, rent, lease, sublicense, assign, transfer, or grant a security interest in your rights in the Application or Services, or authorize all or any portion of the Application or Services to be copied onto another user’s computer except as permitted hereunder;</li>
          <li>Intercept, emulate, or redirect the communication protocols used by the Application or Services in any way, for any purpose, or engage in any activity that interferes with or disrupts the Application or Services or Diamond Sports Recruiting’s or its vendors’ servers or other infrastructure; or</li>
          <li>Facilitate, create, or maintain any unauthorized connection to the Application or Services, including without limitation: (a) any connection to any unauthorized server that emulates, or attempts to emulate, Diamond Sports Recruiting’s or its vendors’ servers; and (b) any connection using programs or tools not approved by Diamond Sports Recruiting in its sole discretion.</li>
        </ul>
        
        <p className='mt-4 max-sm:text-sm'>The Services and Content accessible through the Application are also protected by intellectual property and other laws in the U.S. and in other countries and are subject to limitations on your use thereof, as set forth more fully in the Diamond Sports Recruiting Terms.</p>
        <p className='mt-4 max-sm:text-sm'>As a director or coach of a sports club, athletic director at a high school, college coach, or owner of a college recruiting consulting business that interacts with athletes age 18 years or older, parents of minor children athletes, and athletes that are minors while using the Services and Application, You warrant that: (i) You have the legal right and ability to enter into this Agreement, (ii) You have all necessary rights, licenses, consents, and permissions to use Your Data with the Application and Services, (iii) You are not a competitor of Diamond Sports Recruiting, or someone acting on behalf of a competitor, (iv) You or Your company are in compliance with the Children’s Online Privacy Protection Act (COPPA); (v) Your company retains personal information collected online from a child for only as long as is necessary to fulfill the purpose for which it was collected and deletes the information using reasonable measures to protect against its unauthorized access or use; (vi) You and Your Company do not condition a child’s participation in an online activity on the child providing more information than is reasonably necessary to participate in that activity; (vii) You or Your company shall not post or upload any pictures or videos of children under the age of 18 onto the Application or Services unless a Parent of a minor consents to your doing so; (viii) You and all employees of your company before you are all permitted access to the Application or Services shall be a member in good standing of or licensed by the governing body that oversees the sport You consult or coach in, (ix) You will not sell, share, or profit from the personal information or data of any minor, athlete, or user; (x) You will not sell, share, or profit from the NIL of any minor, athlete, or user; (xi) Your use of the Application or Services will not violate or breach any applicable laws, regulations, or agreements or unreasonably interfere with Our other customers’ use of Our Application or Services. You further warrant that you understand that all laws applicable to this Agreement, including those governing data and privacy, may change regularly and vary by jurisdiction, and You are solely responsible for compliance with any and all applicable laws and regulations.</p>
        
        <h2 className='text-4xl font-bold max-lg:text-2xl max-md:text-xl mt-10'>5. (a) PARENTAL CONSENT</h2>
        <p className='mt-4 max-sm:text-sm'>As the parent of a minor child whose personal information is going to be collected, used, viewed, and uploaded by other Users onto the Application or Services, you agree to the following: (i) You consent to Users who have signed an agreement with Diamond Sports Recruiting to access the Application or Services to post or upload pictures or videos of your minor child revealing their identity onto the Application or Services, (ii) You consent to Users who have signed an agreement with Diamond Sports Recruiting to access the Application or Services to use the Application or Services to collect and internally use your child’s data and/or personal information to track and measure your child’s performance, (iii) You agree that Diamond Sports Recruiting shall have no liability for any damages suffered by you or your child as a result of any User using your child’s data and/or personal information whether such data and/or personal information is used by a User on the Application or Services or not, and (iv) You understand that you have the right to stop any User from using the Application or Services to collect and use data and/or personal information about your child by contacting Diamond Sports Recruiting at: <strong>support@diamondsportsrecruiting.com</strong>.</p>

        <h2 className='text-4xl font-bold max-lg:text-2xl max-md:text-xl mt-10 ml-10'>(b) User Consent</h2>
        <p className='mt-4 max-sm:text-sm'>As a User of the Services age 18 or older whose personal information is going to be collected, used, viewed, and uploaded by other Users onto the Application or Services, you agree to the following: (i) You consent to Users who have signed an agreement with Diamond Sports Recruiting to access the Application or Services to post or upload pictures or videos of you revealing your identity onto the Application or Services, (ii) You consent to Users who have signed an agreement with Diamond Sports Recruiting to access the Application or Services to use the Application or Services to collect and internally use your data and/or personal information to track and measure your performance, (iii) You agree that Diamond Sports Recruiting shall have no liability for any damages suffered by you as a result of any User using your data and/or personal information whether such data and/or personal information is used by a User on the Application or Services or not, and (iv) You understand that you have the right to stop any User from using the Application or Services to collect and use data and/or personal information by contacting Diamond Sports Recruiting at: support@diamondsportsrecruiting.com.</p>

        <h2 className='text-4xl font-bold max-lg:text-2xl max-md:text-xl mt-10'>6. GRANT OF A LIMITED USE LICENSE TO USE THE APPLICATION AND SERVICES</h2>
        <p className='mt-4 max-sm:text-sm'>Diamond Sports Recruiting grants to User and User accepts from Diamond Sports Recruiting, a limited, revocable, non-exclusive, non-transferable right to access and use and permit Authorized Users to access and use the Application and Services solely for the internal business operations of User during the Term. The Application and Services shall not be used by User or by Authorized Users for, or on behalf of, third parties that are not authorized under this Agreement. User shall use its best efforts to ensure that the Authorized Users use the Application and Services in accordance with the terms and conditions of this Agreement. User acknowledges that its right to use the Application and Services will be conditioned upon: (i) User’s payment of the Fees, if any, associated with using the Services; and (ii) the Subscriptions Service being web-based only and will not be installed on any servers owned or controlled by User or otherwise provided to User without Diamond Sports Recruiting's consent.</p>
        <p className='mt-4 max-sm:text-sm'>Subject to your compliance with the Diamond Sports Recruiting Terms and this Agreement, Diamond Sports Recruiting hereby grants, and you hereby accept, a limited, revocable, non-sublicensable, non-exclusive license to engage in non-commercial use of the Application. All rights to use the Application are granted on the condition that such rights are forfeited if you fail to comply with the terms of this Agreement.</p>

        <h2 className='text-4xl font-bold max-lg:text-2xl max-md:text-xl mt-10'>7. USE OF THE APPLICATION</h2>
        <p className='mt-4 max-sm:text-sm'>When you use the Application, you may connect to Diamond Sports Recruiting’s or its vendors’ servers. Your communication with Diamond Sports Recruiting’s properties is governed by the Diamond Sports Recruiting Privacy Policy, available at: <Link href='https://diamondsportsrecruiting.com/privacy-policy' className='text-[#00A3FF]'>https://diamondsportsrecruiting.com/privacy-policy</Link>. You consent to our use of data that you provide or upload to the Application or Services or that we may collect about you through the Application, in compliance with the Privacy Policy.</p>
        <p className='mt-4 max-sm:text-sm'>As part of the Application, you may receive push notifications, text messages, MMS messages, or other types of messages directly sent to you outside or inside the Application (collectively, "Push Messages"). You may control the Push Messages in your device’s or the Application’s settings. Some of the Push Messages may be related to your location or to your use of the Application or Content. Your carrier may charge standard messaging, data, and other fees for use of Push Messages, and these fees may appear on your mobile bill or be deducted from your pre-paid balance. Your carrier may prohibit or restrict certain Push Messages and certain Push Messages may be incompatible with your carrier or mobile device. Contact your carrier with questions regarding these issues. You may discontinue Push Messages in your device’s or the Application’s settings or by deleting the Application. We may collect information related to your use of Push Messages. If you have registered for Push Messages, you agree to notify Diamond Sports Recruiting of any changes to your mobile number, as applicable, and update your account on the Application to reflect this change.</p>
        <p className='mt-4 max-sm:text-sm'>The Application may allow you to access and interoperate with third-party properties, software applications, and data services (collectively, “Third Party Properties”). Diamond Sports Recruiting does not control any Third Party Properties to which you may connect using the Application and is not responsible for the practices of any third party. You acknowledge and agree that Diamond Sports Recruiting is not liable for any loss or damage which may be incurred by you as a result of any reliance placed by you on the completeness, accuracy, or existence of any advertising, products, or other materials on or available from Third Party Properties. You acknowledge that the Application may check for updates to the Application that may be available to you.</p>

        <h2 className='text-4xl font-bold max-lg:text-2xl max-md:text-xl mt-10'>8. WARRANTY DISCLAIMER</h2>
        <p className='mt-4 max-sm:text-sm'>TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, THE APPLICATION, SERVICES, AND CONTENT ARE PROVIDED "AS IS" AND “AS AVAILABLE”, WITH ALL FAULTS AND WITHOUT WARRANTY OF ANY KIND, AND DIAMOND SPORTS RECRUITING AND THE DISTRIBUTION CHANNELS HEREBY DISCLAIM ALL WARRANTIES AND CONDITIONS WITH RESPECT THERETO, EITHER EXPRESS, IMPLIED, OR STATUTORY, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES AND/OR CONDITIONS OF MERCHANTABILITY, NONINFRINGEMENT OF THIRD-PARTY RIGHTS, OF SATISFACTORY QUALITY, OF FITNESS FOR A PARTICULAR PURPOSE, TITLE, OF ACCURACY, OF QUIET ENJOYMENT, OF AVAILABILITY AND AS TO SUBJECT MATTER OF CONTENT. DIAMOND SPORTS RECRUITING DOES NOT WARRANT: (1) THAT THE APPLICATION’S FUNCTIONS OR ANY SERVICES, CONTENT, OR THIRD-PARTY PROPERTIES WILL BE UNINTERRUPTED OR FREE OF ERRORS OR OMISSIONS; (2) THAT DEFECTS WILL BE CORRECTED; (3) THAT THE APPLICATION OR THE SERVERS HOSTING CONTENT ARE FREE OF VIRUSES OR OTHER HARMFUL CODE; OR (4) THAT THE APPLICATION, SERVICES, CONTENT, OR THIRD-PARTY PROPERTIES AVAILABLE THROUGH THE APPLICATION WILL CONTINUE TO BE AVAILABLE. DIAMOND SPORTS RECRUITING SHALL HAVE NO LIABILITY FOR ANY SUCH ISSUES.</p>
        <p className='mt-4 max-sm:text-sm'>YOUR ACCESS TO AND USE OF THE APPLICATION AND SERVICES IS AT YOUR OWN RISK. IF YOU ARE DISSATISFIED WITH THE APPLICATION OR ANY OF THE SERVICES OR CONTENT AVAILABLE THROUGH THE APPLICATION OR SERVICES, YOUR SOLE AND EXCLUSIVE REMEDY IS TO DISCONTINUE ACCESSING AND USING THE APPLICATION</p>
        <p className='mt-4 max-sm:text-sm'>TO THE EXTENT PERMITTED BY LAW THE EXCLUSION OR LIMITATION OF CERTAIN WARRANTIES, OR SOME OR ALL OF THE EXCLUSIONS AND LIMITATIONS IN THIS SECTION MAY NOT APPLY TO YOU.</p>
        
        <h2 className='text-4xl font-bold max-lg:text-2xl max-md:text-xl mt-10'>9. LIMITATION OF LIABILITY/RELEASE OF CLAIMS</h2>
        <p className='mt-4 max-sm:text-sm'>DIAMOND SPORTS RECRUITING WILL NOT BE LIABLE FOR ANY FAILURE OR DELAY IN ITS PERFORMANCE DUE TO ANY CAUSE BEYOND ITS REASONABLE CONTROL, INCLUDING ACTS OF WAR, ACTS OF GOD, ACTS OF THIRD PARTY SERVICE PROVIDERS, EARTHQUAKE, FLOOD, EMBARGO, RIOT, SABOTAGE, LABOR SHORTAGE OR DISPUTE, GOVERNMENTAL ACT, POWER FAILURE OR FAILURE OF THE INTERNET OR COMPUTER EQUIPMENT.</p>
        <p className='mt-4 max-sm:text-sm'>DIAMOND SPORTS RECRUITING WILL NOT BE LIABLE TO YOU OR ANYONE ELSE FOR ANY SPECIAL, INDIRECT, INCIDENTAL, EXEMPLARY, PUNITIVE, OR CONSEQUENTIAL DAMAGES IN CONNECTION WITH THE APPLICATION (INCLUDING THE SERVICES, CONTENT, THIRD-PARTY SERVICES, THIRD-PARTY WEBSITES, OR MESSAGING APPLICATIONS AVAILABLE THROUGH THE APPLICATION OR SERVICES) OR THIS AGREEMENT, EVEN IF FORESEEABLE OR EVEN IF DIAMOND SPORTS RECRUITING HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES (INCLUDING, WITHOUT LIMITATION, WHETHER CAUSED IN WHOLE OR IN PART BY BREACH OF CONTRACT OR WARRANTY, NEGLIGENCE, TORT, GROSS NEGLIGENCE, OR OTHERWISE). DIAMOND SPORTS RECRUITING WILL NOT BE LIABLE TO YOU OR ANYONE ELSE FOR ANY DAMAGES FOR LOSS OF PROFITS, LOSS OF DATA, FUTURE EARNINGS, BUSINESS INTERRUPTION, OR ANY COMMERCIAL DAMAGES, BODILY INJURY DAMAGES, PHYSICAL HARM, EMOTIONAL DISTRESS, DEATH, LOSS OF REPUTATION, LIBEL, SLANDER, OR LOSSES OF ANY KIND. THE FOREGOING LIMITATIONS WILL APPLY EVEN IF ANY STATED REMEDY FAILS OF ITS ESSENTIAL PURPOSE.</p>
        <p className='mt-4 max-sm:text-sm'>DIAMOND SPORTS RECRUITING WILL NOT BE LIABLE TO YOU OR YOUR CHILD FOR ANY LOSSES OR DAMAGES YOU MIGHT SUFFER OF ANY KIND AS A RESULT OF THE ACTIONS OF OTHER USERS: (I) USING YOUR CHILD’S PERSONAL INFORMATION OR DATA AND NIL ON THE APPLICATION OR SERVICES; OR (II) SELLING, SHARING, OR LICENSING USING YOUR CHILD’S PERSONAL INFORMATION OR DATA AND NIL.</p>
        <p className='mt-4 max-sm:text-sm'>DIAMOND SPORTS RECRUITING WILL NOT BE LIABLE TO YOU OR ANY ATHLETE FOR ANY LOSSES OR DAMAGES YOU MIGHT SUFFER OF ANY KIND AS A RESULT OF THE ACTIONS OF OTHER USERS (I) USING YOUR PERSONAL INFORMATION OR DATA AND NIL ON THE APPLICATION OR SERVICES; OR (II) SELLING, SHARING, OR LICENSING USING YOUR PERSONAL INFORMATION OR DATA AND NIL.</p>
        <p className='mt-4 max-sm:text-sm'>YOU ACKNOWLEDGE AND AGREE THAT IF YOU INCUR ANY DAMAGES THAT ARISE OUT OF DIAMOND SPORTS RECRUITING’S ACTS OR OMISSIONS, THE DAMAGES, IF ANY, ARE NOT IRREPARABLE AND ARE NOT SUFFICIENT TO ENTITLE YOU TO AN INJUNCTION OR OTHER EQUITABLE RELIEF RESTRICTING EXPLOITATION OF ANY WEBSITE, PROPERTY, PRODUCT, OR OTHER AUDIO/VISUAL CONTENT OWNED, CONTROLLED, OR DISTRIBUTED BY DIAMOND SPORTS RECRUITING, INCLUDING WITHOUT LIMITATION THE APPLICATION OR SERVICES.</p>
        <p className='mt-4 max-sm:text-sm'>SOME JURISDICTIONS DO NOT ALLOW LIMITATIONS ON IMPLIED WARRANTIES OR THE EXCLUSION OR LIMITATION OF CERTAIN DAMAGES, SO SOME OF THE ABOVE LIMITATIONS AND EXCLUSIONS MAY NOT APPLY TO YOU.</p>

        <h2 className='text-4xl font-bold max-lg:text-2xl max-md:text-xl mt-10'>10. INDEMNITY</h2>
        <p className='mt-4 max-sm:text-sm'>You will indemnify, defend, and hold Diamond Sports Recruiting and all of its officers, directors, owners, employees, agents, information providers, service providers, vendors, contractors, affiliates, partners, and licensors (collectively, the “Diamond Sports Recruiting Indemnified Parties”) harmless from and against any and all liability, losses, costs, and expenses (including attorneys’ fees) incurred by any of the Diamond Sports Recruiting Indemnified Parties in connection with any claim, including, but not limited to, claims for defamation, violation of rights of publicity or privacy, copyright infringement, or trademark infringement arising out of: your use of the Application; any use or alleged use of your account or your passwords by any person, whether or not authorized by you; your data; your unlawful sale or sharing of the data of any athlete or user without their consent or minor child without parental consent; your unlawful sale or sharing of the NIL of a minor, athlete, or user; your connection to Diamond Sports Recruiting’s or its vendors’ servers; your violation of this Agreement; or your violation of the rights of any other person or entity. Diamond Sports Recruiting reserves the right, at its own expense, to assume the exclusive defense and control of any matter for which you are required to indemnify Diamond Sports Recruiting, and you will cooperate with Diamond Sports Recruiting’s defense of these claims.</p>

        <h2 className='text-4xl font-bold max-lg:text-2xl max-md:text-xl mt-10'>11. TERMINATION</h2>
        <p className='mt-4 max-sm:text-sm'>This Agreement is effective until terminated. You may terminate this Agreement at any time by: (i) irretrievably erasing, deleting, or destroying all copies of the Application in your possession or control; and (ii) ceasing to use the Services and Content available through the Application. Diamond Sports Recruiting may terminate this Agreement at any time for any reason or no reason. Upon termination for any reason, the license granted in Section 4 will immediately terminate. The provisions in Sections 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 13, 14, 15, and 16 will survive any termination.</p>

        <h2 className='text-4xl font-bold max-lg:text-2xl max-md:text-xl mt-10'>12. EXPORT CONTROLS</h2>
        <p className='mt-4 max-sm:text-sm'>You may not use or otherwise export or re-export the Application or elements thereof except as authorized by United States law and the laws of the jurisdiction in which the Services was accessed or obtained. In particular, but without limitation, the Application may not be exported or re-exported (a) into any U.S.-embargoed countries or (b) to anyone on the U.S. Treasury Department's Specially Designated Nationals List or the U.S. Department of Commerce Denied Person’s List or Entity List. By using the Application, you represent and warrant that it is not located in any such country or on any such list. You also agree that you will not use the Application for any purposes prohibited by applicable law.</p>

        <h2 className='text-4xl font-bold max-lg:text-2xl max-md:text-xl mt-10'>13. CONSENT TO USE OF DATA</h2>
        <p className='mt-4 max-sm:text-sm'>You agree that Diamond Sports Recruiting may collect and use technical data and related information—including but not limited to technical information about your device, system, and application software, and peripherals—that is gathered periodically to facilitate the provision of software updates, product support, and other services to you (if any) related to the Licensed Application.</p>
        <p className='mt-4 max-sm:text-sm'>Your Data also may include your name, email addresses, telephone numbers, and any information provided that identifies You that is uploaded to the Services pertaining to your birth date, social security number, data, or metrics related to Your Performance as an athlete and personally identifiable information (PII) including financial information. You have designed, created, and provided all of your data without the participation or involvement of Diamond Sports Recruiting. You are responsible for any actions you take with respect to Data, including uploading it to the Services or using the Services to share or otherwise make available such Data to third parties. You are responsible for ensuring that you have all the rights and permissions needed to use Data in connection with the Services. You Shall have the sole responsibility for the accuracy, quality, integrity, legality, and reliability of, and copyright permissions for, all Data entered into the Services. Diamond Sports Recruiting assumes no responsibility for the accuracy, propriety, or usefulness to You of the Data. Diamond Sports Recruiting shall not be liable to You or any third parties for any loss, damage, or expense whatsoever and howsoever arising from any Data entered into the Services by You or by an entity on its behalf unless such data is protected under federal or state law. You acknowledge that Diamond Sports Recruiting will rely on the accuracy of the Data provided to Diamond Sports Recruiting by You as it performs its requested functions under this Agreement. You acknowledge that you own all of the Data or have all rights to grant such licenses to Diamond Sports Recruiting to use such Information in furtherance of providing the Services without infringement or violation of any third-party rights. Diamond Sports Recruiting provides no warranties, representations, or indemnification to You for its access to, and use of the Data.</p>
        <p className='mt-4 max-sm:text-sm'>You grant a revocable license and consent to Diamond Sports Recruiting’s use of data that you provide or that we may collect about you through the Application, in compliance with Our Privacy Policy. You give consent to Diamond Sports Recruiting to use the Data when integrating with third-party company systems to perform services on Diamond Sports Recruiting’s behalf relating to the functionality of the Services and that You consent to Diamond Sports Recruiting using Data that may include protected health information and personally identifiable information containing social security numbers and credit card information. We will only use such data with our partners or service providers who perform functions to enable Diamond Sports Recruiting to provide its Services.</p>
        <p className='mt-4 max-sm:text-sm'>You acknowledge and agree that Diamond Sports Recruiting shall have the right to use any data collected or created by You in your use of the Application related to selling, publishing, disclosing, or sharing combined data and information from many Users with our partners in order to help our partners market and sell our Products pursuant to written agreements with confidentiality, privacy, and security obligations. All such information includes data derived from personal information in aggregated, anonymous form and does not identify You individually.</p>
        <p className='mt-4 max-sm:text-sm'>You give consent to Diamond Sports Recruiting to disclose or share with any of our affiliated companies or our partners any aggregated, anonymized information about you that does not identify you individually, without restriction as explained in our Privacy Policy.</p>

        <h2 className='text-4xl font-bold max-lg:text-2xl max-md:text-xl mt-10'>14. Name, Likeness, and Image (“NIL”)</h2>
        <p className='mt-4 max-sm:text-sm'><strong>Definition of terms</strong>: a. “Athlete” shall mean any person who participates in an organized sport, is a member of a team or club, and whose personal information is uploaded to the Application or Services. b. "Name, Image, and Likeness" or "NIL" shall mean any athlete’s individual names, signatures, photographs, images, likenesses, voices, and any other indicia of their identities. c. By using the Application or Services you are not granted any license or right to use, sell, market, or profit from the NIL of any athlete, minor, or user.</p>

        <h2 className='text-4xl font-bold max-lg:text-2xl max-md:text-xl mt-10'>15. APPLICABLE LAW</h2>
        <p className='mt-4 max-sm:text-sm'>By using the Application and Services you agree that the laws of the State of Kansas without regard to principles of conflict of laws, will govern this Agreement and any dispute of any sort that might arise between You and Diamond Sports Recruiting.</p>

        <h2 className='text-4xl font-bold max-lg:text-2xl max-md:text-xl mt-10'>16. DISPUTES</h2>
        <p className='mt-4 max-sm:text-sm'>ANY DISPUTE RELATING IN ANY WAY TO THIS AGREEMENT AND YOUR USE OF DIAMOND SPORTS RECRUITING’S WEBSITE, APPLICATION, OR SERVICES SHALL BE SUBMITTED TO CONFIDENTIAL BINDING ARBITRATION IN JOHNSON COUNTY, KANSAS EXCEPT FOR INTELLECTUAL PROPERTY CLAIMS BROUGHT BY EITHER PARTY (WHICH FOR PURPOSES OF THIS SECTION DO NOT INCLUDE PRIVACY AND PUBLICITY CLAIMS) AND CLAIMS THAT MAY BE BROUGHT IN SMALL-CLAIMS COURT.</p>
        <p className='mt-4 max-sm:text-sm'>CONFIDENTIAL ARBITRATION UNDER THIS AGREEMENT SHALL BE RESOLVED EXCLUSIVELY UNDER THE CONSUMER ARBITRATION RULES THEN PREVAILING OF THE AMERICAN ARBITRATION ASSOCIATION ("AAA'S CONSUMER RULES"), EXCLUDING ANY RULES AND PROCEDURES GOVERNING OR PERMITTING CLASS OR REPRESENTATIVE ACTIONS. THE RULES ARE AVAILABLE AT THE AMERICAN ARBITRATION ASSOCIATION'S WEBSITE. YOU AND DIAMOND SPORTS RECRUITING AGREE TO EXPRESSLY WAIVE ANY RIGHTS TO FILE CLASS OR REPRESENTATIVE ACTIONS OR SEEK RELIEF ON A CLASS OR REPRESENTATIVE BASIS IN ANY JURISDICTION OR FORUM.</p>
        <p className='mt-4 max-sm:text-sm'>THE ARBITRATOR SHALL APPLY KANSAS LAW, AND THE ARBITRATOR'S AWARD SHALL BE BINDING AND MAY BE ENTERED AS A JUDGMENT IN ANY COURT OF COMPETENT JURISDICTION. THERE SHALL BE NO APPEAL FROM ANY AWARD OF THE ARBITRATOR. TO THE FULLEST EXTENT PERMITTED BY APPLICABLE LAW, NO ARBITRATION UNDER THIS AGREEMENT SHALL BE JOINED TO AN ARBITRATION INVOLVING ANY OTHER PARTY SUBJECT TO THIS AGREEMENT, WHETHER THROUGH CLASS ARBITRATION PROCEEDINGS OR OTHERWISE. IF ANY PART OF THIS ARBITRATION PROVISION IS FOUND TO BE INVALID, UNENFORCEABLE, OR ILLEGAL, THE REST OF THIS PROVISION SHALL REMAIN IN EFFECT.</p>
        <p className='mt-4 max-sm:text-sm'>IF THE ENTIRE ARBITRATION PROVISION IS FOUND TO BE INVALID OR UNENFORCEABLE, THEN THE PARTIES CONSENT TO PERSONAL JURISDICTION AND EXCLUSIVE VENUE IN THE STATE AND FEDERAL COURTS IN KANSAS.</p>
        <p className='mt-4 max-sm:text-sm'>If you initiate the arbitration, your arbitration fees will be limited to the filing fee set forth in the AAA's Consumer Rules.</p>

        <h2 className='text-4xl font-bold max-lg:text-2xl max-md:text-xl mt-10'>17. MISCELLANEOUS</h2>
        <p className='mt-4 max-sm:text-sm'>This Agreement constitutes the entire agreement between the parties with respect to its subject matter and supersedes any prior oral or written agreements, provided, however, that this Agreement will coexist with the Diamond Sports Recruiting Terms and any Additional Terms. To the extent that the provisions of this Agreement conflict with the Diamond Sports Recruiting Terms, this Agreement will govern. We may be required by state or federal law to notify you of certain events. You hereby acknowledge and agree that such notices will be effective upon our posting them on our sites or delivering them to you via email if you have provided it to us. If you do not provide us with accurate information or we do not have access to your email address, we will not be responsible for failure to notify you. If any part of this Agreement is determined to be invalid or unenforceable under applicable law, that provision will be removed, and the remainder of the Agreement will continue to be valid and enforceable, except as expressly stated. Our failure to exercise or enforce any right or provision in this Agreement will not constitute a waiver of such right or provision. Except as otherwise required by law, the controlling language of this Agreement is English. This Agreement will be binding upon and will inure to the benefit of the parties, their successors, and permitted assigns.</p>

        <h2 className='text-4xl font-bold max-lg:text-2xl max-md:text-xl mt-10'>18. CONTACT INFORMATION</h2>
        <p className='mt-4 max-sm:text-sm'>You may contact Diamond Sports Recruiting at: <Link className='text-[#00A3FF]' href='support@diamondsportsrecruiting.com'>support@diamondsportsrecruiting.com</Link>.</p>
        <p className='mt-4 max-sm:text-sm'>If you have any questions, claims, or complaints, you should notify us at <Link className='text-[#00A3FF]' href='support@diamondsportsrecruiting.com'>support@diamondsportsrecruiting.com</Link>.</p>
        <p className='mt-4 max-sm:text-sm'>You hereby acknowledge that you have read and understood this Agreement and agree that by clicking “Accept” or by installing, copying, or using the Application and Services you are acknowledging your agreement to be bound by this Agreement.</p>
      </div>
    </>
  )
}

export default page